version = 0.1
[default.deploy.parameters]
stack_name = "mvp-stories-demo"
resolve_s3 = true
s3_prefix = "mvp-stories-demo"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
